### ISSUE TITLE
Conversion to GTIN14

### ISSUE THREAD

**Issue by 3zzy** [violuke/php-barcodes#1]
```
if ($bc_validator->isValid()) {
  echo($bc_validator->getType(), 'Type');
  echo($bc_validator->getBarcode(), 'Barcode');
  echo($bc_validator->getGTIN14(), 'GTIN14');
}
```

```
Type: UPC
Barcode: 740668124518
GTIN14: 00740668124518
```

`00740668124518` is incorrect, in GTIN14 it should be `0740668124518`

**Comment by violuke** [comment]
Thanks @3zzy, but are you sure?

Your GTIN14 only has 13 digits. My understanding is that would make it in GTIN13.

If you navigate to www.gs1.org/check-digit-calculator and then enter `74066812451` (note the missing check digit from the end), it tells you `You've entered 11 digits, this corresponds with the GTIN-12 format.` If you the click the link which says `See this in GTIN 14 format`, you'll see (including check digit) `00740668124518`.

I'm pretty sure that this library is functioning correctly, but if you still disagree then do please explain. Thanks.
